// One definition of "what version of the repo-mode engine is this", shared by the thing that
// writes the stamp (scripts/build-engine.mjs) and the thing that checks it (src/doctor.js).
//
// It lives in src/ rather than scripts/ for a concrete reason: scripts/ is not in the npm tarball
// (see package.json "files"), so a doctor that imported the generator would throw for every real
// user while working perfectly in this checkout. And it is shared rather than copied because this
// file exists at all as a consequence of a hand-copied security routine drifting nine credential
// patterns behind its original — duplicating the check for the duplication problem would be a poor
// joke to leave in the repository.
//
// WHY THE STAMP IS COMPUTED AND NOT READ. The engine carries `const ENGINE_STAMP = '<hex>'` as a
// human-readable marker, and the first version of the staleness check simply compared that literal
// against ours. A literal is the file's own claim about itself, and a claim survives edits: with
// the containment guard cut out of an installed engine by hand — a two-line change disabling the
// check that stops notes being written outside the repo — the file still declared the current
// stamp, and doctor reported "matches the engine this copy installs". Verified, not theorised.
//
// So both sides are hashed from content. The declared literal is still useful for exactly one
// thing: an engine that carries no stamp line at all predates stamping entirely, which is a
// distinct and much older state, and worth its own message.

import { createHash } from 'node:crypto';

// The stamp line is excluded from the hash it produces — a digest cannot cover the bytes it is
// written into. Blanking rather than deleting keeps generation a fixed point: hashing an
// already-stamped file blanks the same line and arrives at the same digest.
export const STAMP_LINE = /^const ENGINE_STAMP = '[a-f0-9]*';$/m;

// Line endings are normalised first. git checks this file out with CRLF on Windows and LF
// elsewhere, and a stamp that changed with the checkout would report every POSIX user's engine as
// stale against a Windows-built package, which is noise indistinguishable from the real signal.
export function engineStamp(engineText) {
  return createHash('sha256')
    .update(String(engineText).replace(/\r\n/g, '\n').replace(STAMP_LINE, "const ENGINE_STAMP = '';"))
    .digest('hex')
    .slice(0, 12);
}

// The stamp the file claims for itself, or null if it carries no stamp line. Only used to tell
// "generated before stamping existed" apart from "generated by a different build".
export function declaredStamp(engineText) {
  const m = String(engineText).match(/^const ENGINE_STAMP = '([a-f0-9]*)';$/m);
  return m ? m[1] : null;
}
